name: Release Drafter

on:
  push:
    branches:
      - main
      - hotfix/**
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

permissions:
  contents: read

jobs:
  update-release-draft:
    name: Update Release Drafter
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
    steps:
      - name: Release drafter
        # if: ${{ github.ref_name == 'main' || github.base_ref == 'main' }}
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-main.yml
          commitish: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Release drafter (Hotfix)
      #   if: ${{ contains(github.ref_name, 'release/v') || contains(github.base_ref, 'release/v') }}
      #   uses: release-drafter/release-drafter@v6
      #   with:
      #     config-name: release-drafter-hotfix.yml
      #     commitish: ${{ github.ref_name }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}